Better sourcing

diff --git a/etc/bashrc b/etc/bashrc
--- a/etc/bashrc
+++ b/etc/bashrc
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 
+# Handle OpenFOAM environment sourcing and tweaks:
+if [ ! -f "/opt/openfoam13/etc/bashrc" ]; then
+    echo "OpenFOAM environment not found."
+    exit 1
+fi
+
+# Pre-source full OpenFOAM environment:
+source /opt/openfoam13/etc/bashrc
+
 # Path to this script:
 SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
@@ -7,24 +16,19 @@ SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
 
 # Path to scripts directory:
-PROJECT_SRC="${PROJECT_DIR}/script"
+PROJECT_RCS="${SCRIPT_DIR}/rc"
 
-# Handle OpenFOAM environment sourcing and tweaks:
-if [ -f "/opt/openfoam13/etc/bashrc" ]; then
-    # Pre-source full OpenFOAM environment:
-    source /opt/openfoam13/etc/bashrc
-
-    # Tweak OpenFOAM environment variables:
-    WM_PROJECT_USER_DIR="${PROJECT_DIR}"
-    FOAM_RUN="${PROJECT_DIR}/run"
-    FOAM_USER_APPBIN="${PROJECT_DIR}/platforms/${WM_OPTIONS}/bin"
-    FOAM_USER_LIBBIN="${PROJECT_DIR}/platforms/${WM_OPTIONS}/lib"
-fi
+# Tweak OpenFOAM environment variables:
+export WM_PROJECT_USER_DIR="${PROJECT_DIR}"
+export FOAM_RUN="${PROJECT_DIR}/run"
+export FOAM_USER_APPBIN="${PROJECT_DIR}/platforms/${WM_OPTIONS}/bin"
+export FOAM_USER_LIBBIN="${PROJECT_DIR}/platforms/${WM_OPTIONS}/lib"
 
 # Source all *rc files in the script directory:
-if [ -d "${PROJECT_SRC}" ]; then
-    for rc_file in "${PROJECT_SRC}"/*rc; do
+if [ -d "${PROJECT_RCS}" ]; then
+    for rc_file in "${PROJECT_RCS}"/*rc; do
         if [ -f "${rc_file}" ]; then
+            # echo "Sourcing ${rc_file}"
             source "${rc_file}"
         fi
     done
